ALTER TABLE empresas DISABLE ROW LEVEL SECURITY;
ALTER TABLE usuarios DISABLE ROW LEVEL SECURITY;
ALTER TABLE pacientes DISABLE ROW LEVEL SECURITY;
ALTER TABLE evoluciones DISABLE ROW LEVEL SECURITY;
ALTER TABLE indicaciones DISABLE ROW LEVEL SECURITY;
ALTER TABLE administracion_med DISABLE ROW LEVEL SECURITY;
