"""Catalogo CIE-10/11 embebido. Codigos frecuentes para Argentina con utilidades de busqueda."""

CATEGORIAS = [
    "Infecciosas", "Neoplasias", "Endocrinas", "Mentales", "Nervioso",
    "Circulatorio", "Respiratorio", "Digestivo", "Piel", "Osteomuscular",
    "Genitourinario", "Oftalmologicas", "Otorrinolaringologicas", "Embarazo",
    "Perinatal", "Sintomas", "Traumatismos",
]

# (codigo, descripcion, categoria_idx) — ~250 codigos de alta frecuencia Argentina
_CIE10_RAW = [
    ("A09","Diarrea/gastroenteritis infecciosa",0), ("A15","Tuberculosis respiratoria",0),
    ("A36","Difteria",0), ("A37","Tos convulsa",0), ("A38","Escarlatina",0),
    ("A39","Infeccion meningococica",0), ("A40","Septicemia estreptococica",0),
    ("A41","Otras septicemias",0), ("A46","Erisipela",0), ("A49","Infeccion bacteriana NE",0),
    ("A51","Sifilis primaria",0), ("A53","Sifilis NE",0), ("A54","Infeccion gonococica",0),
    ("A60","Infeccion herpetica anogenital",0), ("A64","ETS NE",0),
    ("A80","Poliomielitis aguda",0), ("A82","Rabia",0), ("A90","Dengue",0),
    ("B00","Infecciones por herpesvirus",0), ("B01","Varicela",0),
    ("B02","Herpes zoster",0), ("B05","Sarampion",0), ("B06","Rubiola",0),
    ("B07","Verrugas virales",0), ("B15","Hepatitis A aguda",0),
    ("B16","Hepatitis B aguda",0), ("B17","Otras hepatitis virales agudas",0),
    ("B18","Hepatitis viral cronica",0), ("B20","VIH con enfermedades infecciosas",0),
    ("B24","VIH NE",0), ("B26","Parotiditis (paperas)",0),
    ("B27","Mononucleosis infecciosa",0), ("B35","Dermatofitosis (tina)",0),
    ("B37","Candidiasis",0), ("B44","Aspergilosis",0), ("B49","Micosis NE",0),
    ("B50","Paludismo falciparum",0), ("B54","Paludismo NE",0),
    ("B55","Leishmaniasis",0), ("B57","Enfermedad de Chagas",0),
    ("B58","Toxoplasmosis",0), ("B65","Esquistosomiasis",0),
    ("B67","Equinococosis (hidatidosis)",0), ("B77","Ascariasis",0),
    ("B80","Enterobiasis (oxiuriasis)",0), ("B85","Pediculosis",0),
    ("B86","Escabiosis (sarna)",0), ("B99","Otras infecciosas",0),
    ("C16","Neoplasia maligna de estomago",1), ("C18","Neoplasia maligna de colon",1),
    ("C20","Neoplasia maligna de recto",1), ("C22","Neoplasia maligna de higado",1),
    ("C25","Neoplasia maligna de pancreas",1), ("C34","Neoplasia bronquio/pulmon",1),
    ("C43","Melanoma maligno de piel",1), ("C44","Otras neoplasias piel",1),
    ("C50","Neoplasia maligna de mama",1), ("C53","Neoplasia cuello uterino",1),
    ("C54","Neoplasia cuerpo uterino",1), ("C56","Neoplasia de ovario",1),
    ("C61","Neoplasia de prostata",1), ("C62","Neoplasia de testiculo",1),
    ("C64","Neoplasia de rinon",1), ("C67","Neoplasia de vejiga",1),
    ("C71","Neoplasia de encefalo",1), ("C73","Neoplasia de tiroides",1),
    ("C80","Neoplasia maligna NE",1), ("C81","Enfermedad de Hodgkin",1),
    ("C83","Linfoma no Hodgkin difuso",1), ("C90","Mieloma multiple",1),
    ("C91","Leucemia linfatica",1), ("C92","Leucemia mieloide",1),
    ("D25","Leiomioma uterino",1), ("D27","Neoplasia benigna de ovario",1),
    ("D50","Anemia por deficiencia de hierro",2), ("D51","Anemia por deficiencia B12",2),
    ("D52","Anemia por deficiencia folato",2), ("D53","Otras anemias nutricionales",2),
    ("D57","Anemia falciforme",2), ("D59","Anemia hemolitica adquirida",2),
    ("D60","Aplasia eritrocitica",2), ("D61","Otras anemias aplasicas",2),
    ("D62","Anemia posthemorragica aguda",2), ("D64","Anemia NE",2),
    ("D65","Coagulacion intravascular diseminada",2), ("D66","Deficiencia factor VIII",2),
    ("D68","Otros defectos coagulacion",2), ("D69","Purpura/otros hemorragicos",2),
    ("D70","Agranulocitosis",2), ("D72","Otras leucopenias",2),
    ("D73","Enfermedades del bazo",2), ("D86","Sarcoidosis",2),
    ("E03","Hipotiroidismo",2), ("E04","Bocio no toxico",2),
    ("E05","Hipertiroidismo",2), ("E06","Tiroiditis",2),
    ("E10","Diabetes tipo 1",2), ("E11","Diabetes tipo 2",2),
    ("E14","Diabetes NE",2), ("E15","Coma hipoglucemico no diabetico",2),
    ("E16","Otros trastornos pancreas interno",2), ("E21","Hiperparatiroidismo",2),
    ("E24","Sindrome de Cushing",2), ("E27","Otros trastornos suprarrenales",2),
    ("E28","Disfuncion ovarica",2), ("E29","Disfuncion testicular",2),
    ("E44","Desnutricion moderada/leve",2), ("E46","Desnutricion NE",2),
    ("E55","Deficiencia vitamina D",2), ("E66","Obesidad",2),
    ("E78","Trastornos metabolismo lipoproteinas",2), ("E84","Fibrosis quistica",2),
    ("E86","Deshidratacion",2), ("E87","Trastornos hidroelectroliticos",2),
    ("F00","Demencia Alzheimer",3), ("F01","Demencia vascular",3),
    ("F03","Demencia NE",3), ("F05","Delirio (confusion aguda)",3),
    ("F10","Trastornos por alcohol",3), ("F11","Trastornos por opiaceos",3),
    ("F12","Trastornos por cannabis",3), ("F14","Trastornos por cocaina",3),
    ("F17","Trastornos por tabaco",3), ("F20","Esquizofrenia",3),
    ("F22","Trastorno delirante persistente",3), ("F23","Trastorno psicotico agudo",3),
    ("F25","Trastorno esquizoafectivo",3), ("F29","Psicosis NE",3),
    ("F30","Episodio maniaco",3), ("F31","Trastorno bipolar",3),
    ("F32","Episodio depresivo mayor",3), ("F33","Trastorno depresivo recurrente",3),
    ("F34","Trastornos animo persistentes",3), ("F39","Trastorno animo NE",3),
    ("F40","Trastornos fobico-ansiosos",3), ("F41","Otros trastornos ansiedad",3),
    ("F42","TOC",3), ("F43","Trastornos por estres",3),
    ("F44","Trastornos disociativos",3), ("F45","Trastornos somatomorfos",3),
    ("F50","Trastornos conducta alimentaria",3), ("F51","Trastornos sueno NE",3),
    ("F60","Trastornos especificos personalidad",3), ("F70","Retraso mental leve",3),
    ("F71","Retraso mental moderado",3), ("F79","Retraso mental NE",3),
    ("F80","Trastornos habla/lenguaje",3), ("F81","Trastornos aprendizaje",3),
    ("F84","Trastornos espectro autista",3), ("F90","TDAH",3),
    ("F91","Trastornos de la conducta",3), ("F99","Trastorno mental NE",3),
    ("G20","Parkinson",4), ("G30","Alzheimer",4), ("G35","Esclerosis multiple",4),
    ("G40","Epilepsia",4), ("G41","Estado epileptico",4),
    ("G43","Migrana",4), ("G44","Otras cefaleas",4),
    ("G45","AIT (ataque isquemico transitorio)",4), ("G47","Trastornos sueno organicos",4),
    ("G50","Trastornos del trigemino",4), ("G51","Paralisis facial",4),
    ("G54","Trastornos raices nerviosas",4), ("G56","Mononeuropatias MS",4),
    ("G57","Mononeuropatias MI",4), ("G60","Neuropatia hereditaria",4),
    ("G61","Polineuropatia inflamatoria",4), ("G62","Otras polineuropatias",4),
    ("G70","Miastenia gravis",4), ("G71","Trastornos musculares primarios",4),
    ("G80","Paralisis cerebral infantil",4), ("G81","Hemiplejia",4),
    ("G82","Paraplejia/tetraplejia",4), ("G91","Hidrocefalia",4),
    ("G93","Otros trastornos encefalo",4), ("G95","Enfermedades medula espinal",4),
    ("I10","Hipertension esencial",5), ("I11","Cardiopatia hipertensiva",5),
    ("I15","Hipertension secundaria",5), ("I20","Angina de pecho",5),
    ("I21","IAM (infarto agudo miocardio)",5), ("I25","Cardiopatia isquemica cronica",5),
    ("I26","Embolia pulmonar",5), ("I27","Cardiopulmonar otras",5),
    ("I30","Pericarditis aguda",5), ("I33","Endocarditis infecciosa",5),
    ("I34","Trastornos mitral no reumaticos",5), ("I35","Trastornos aorticos no reumaticos",5),
    ("I40","Miocarditis aguda",5), ("I42","Miocardiopatia dilatada",5),
    ("I44","Bloqueo AV/rama",5), ("I46","Paro cardiaco",5),
    ("I47","Taquicardias paroxisticas",5), ("I48","Fibrilacion auricular",5),
    ("I49","Otras arritmias",5), ("I50","Insuficiencia cardiaca",5),
    ("I60","Hemorragia subaracnoidea",5), ("I61","Hemorragia intracerebral",5),
    ("I63","Infarto cerebral",5), ("I64","ACV NE",5),
    ("I67","Otras enfermedades cerebrovasculares",5), ("I69","Secuelas ACV",5),
    ("I70","Aterosclerosis",5), ("I71","Aneurisma aortico",5),
    ("I73","Enf vasculares perifericas",5), ("I74","Embolia/trombosis arterial",5),
    ("I80","Tromboflebitis superficial",5), ("I82","Otras embolias venosas",5),
    ("I83","Varices miembros inferiores",5), ("I84","Hemorroides",5),
    ("I95","Hipotension",5), ("J00","Rinofaringitis aguda (resfrio)",6),
    ("J01","Sinusitis aguda",6), ("J02","Faringitis aguda",6),
    ("J03","Amigdalitis aguda",6), ("J04","Laringitis/traqueitis aguda",6),
    ("J06","Infeccion respiratoria alta NE",6), ("J10","Gripe virus identificado",6),
    ("J11","Gripe virus NE",6), ("J12","Neumonia viral",6),
    ("J13","Neumonia por Streptococcus",6), ("J14","Neumonia por Haemophilus",6),
    ("J15","Neumonia bacteriana NE",6), ("J18","Neumonia NE",6),
    ("J20","Bronquitis aguda",6), ("J21","Bronquiolitis aguda",6),
    ("J22","Infeccion respiratoria baja aguda",6), ("J30","Rinitis alergica/vasomotora",6),
    ("J31","Rinitis cronica",6), ("J32","Sinusitis cronica",6),
    ("J33","Polipo nasal",6), ("J35","Amigdalitis cronica/hipertrofia",6),
    ("J36","Absceso periamigdalino",6), ("J38","Enfermedades cuerdas vocales",6),
    ("J40","Bronquitis NE",6), ("J41","Bronquitis cronica simple",6),
    ("J42","Bronquitis cronica NE",6), ("J43","Enfisema",6),
    ("J44","EPOC",6), ("J45","Asma",6), ("J46","Estado asmatico",6),
    ("J47","Bronquiectasia",6), ("J80","SDRA",6), ("J81","Edema pulmonar",6),
    ("J84","Enf pulmonares intersticiales",6), ("J85","Absceso de pulmon",6),
    ("J86","Piotorax (empiema)",6), ("J90","Derrame pleural",6),
    ("J93","Neumotorax",6), ("J96","Insuficiencia respiratoria",6),
    ("J98","Otros trastornos respiratorios",6),
    ("K02","Caries dental",7), ("K04","Enfermedades pulpa/periapicales",7),
    ("K05","Gingivitis/enfermedad periodontal",7), ("K12","Estomatitis",7),
    ("K20","Esofagitis",7), ("K21","ERGE (reflujo)",7),
    ("K25","Ulcera gastrica",7), ("K26","Ulcera duodenal",7),
    ("K27","Ulcera peptica NE",7), ("K29","Gastritis/duodenitis",7),
    ("K30","Dispepsia",7), ("K31","Otros trastornos estomago",7),
    ("K35","Apendicitis aguda",7), ("K37","Apendicitis NE",7),
    ("K40","Hernia inguinal",7), ("K42","Hernia umbilical",7),
    ("K44","Hernia diafragmatica",7), ("K50","Enfermedad de Crohn",7),
    ("K51","Colitis ulcerosa",7), ("K52","Otras colitis no infecciosas",7),
    ("K56","Ileo/obstruccion",7), ("K57","Enfermedad diverticular",7),
    ("K58","SII (intestino irritable)",7), ("K59","Otros funcionales intestinales",7),
    ("K60","Fisura/fistula anal",7), ("K61","Absceso anal/rectal",7),
    ("K65","Peritonitis",7), ("K70","Enfermedad alcoholica higado",7),
    ("K71","Hepatopatia toxica",7), ("K72","Insuficiencia hepatica",7),
    ("K73","Hepatitis cronica",7), ("K74","Fibrosis/cirrosis hepatica",7),
    ("K75","Otras hepaticas inflamatorias",7), ("K76","Otras enfermedades higado",7),
    ("K80","Colelitiasis (calculos biliares)",7), ("K81","Colecistitis",7),
    ("K83","Otras vias biliares",7), ("K85","Pancreatitis aguda",7),
    ("K86","Pancreatitis cronica",7), ("K92","Otras enfermedades digestivas",7),
    ("L01","Impétigo",8), ("L02","Absceso cutaneo/forunculo",8),
    ("L03","Celulitis",8), ("L05","Quiste pilonidal",8),
    ("L08","Otras infecciones piel",8), ("L20","Dermatitis atopica",8),
    ("L21","Dermatitis seborreica",8), ("L22","Dermatitis del panal",8),
    ("L23","Dermatitis alergica contacto",8), ("L24","Dermatitis irritativa",8),
    ("L25","Dermatitis contacto NE",8), ("L27","Dermatitis por ingestion",8),
    ("L28","Liquen simple/prurigo",8), ("L29","Prurito",8),
    ("L30","Otras dermatitis",8), ("L40","Psoriasis",8),
    ("L42","Pitiriasis rosada",8), ("L43","Liquen plano",8),
    ("L50","Urticaria",8), ("L51","Eritema multiforme",8),
    ("L52","Eritema nudoso",8), ("L55","Quemadura solar",8),
    ("L60","Trastornos unas",8), ("L63","Alopecia areata",8),
    ("L64","Alopecia androgenetica",8), ("L70","Acne",8),
    ("L71","Rosacea",8), ("L72","Quistes foliculares",8),
    ("L80","Vitiligo",8), ("L81","Otros trastornos pigmentacion",8),
    ("L82","Queratosis seborreica",8), ("L84","Callos/helomas",8),
    ("L89","Ulcera por presion (escaras)",8), ("L93","Lupus eritematoso discoide",8),
    ("L97","Ulcera miembro inferior",8), ("L98","Otros trastornos piel",8),
    ("M00","Artritis piogenica",9), ("M05","Artritis reumatoidea seropositiva",9),
    ("M06","Otra artritis reumatoidea",9), ("M08","Artritis juvenil",9),
    ("M10","Gota",9), ("M13","Artritis NE",9),
    ("M15","Poliartrosis",9), ("M16","Coxartrosis (cadera)",9),
    ("M17","Gonartrosis (rodilla)",9), ("M19","Otras artrosis",9),
    ("M23","Trastornos internos rodilla",9), ("M24","Otros trastornos articulares",9),
    ("M25","Otros trastornos articulares NE",9), ("M32","Lupus eritematoso sistemico",9),
    ("M33","Dermatomiositis/polimiositis",9), ("M34","Esclerosis sistemica",9),
    ("M35","Otras enfermedades tejido conjuntivo",9), ("M40","Cifosis/lordosis",9),
    ("M41","Escoliosis",9), ("M45","Espondilitis anquilosante",9),
    ("M47","Espondilosis (artrosis vertebral)",9), ("M50","Trastornos disco cervical",9),
    ("M51","Trastornos disco lumbar",9), ("M54","Dorsalgia (lumbago/ciatica)",9),
    ("M60","Miositis",9), ("M62","Otros trastornos musculares",9),
    ("M65","Sinovitis/tenosinovitis",9), ("M70","Trastornos tejidos blandos sobreuso",9),
    ("M75","Lesiones del hombro",9), ("M79","Otros trastornos tejidos blandos",9),
    ("M80","Osteoporosis con fractura",9), ("M81","Osteoporosis sin fractura",9),
    ("M84","Trastornos continuidad osea",9), ("M86","Osteomielitis",9),
    ("M87","Osteonecrosis",9), ("M88","Enfermedad de Paget",9),
    ("M94","Otros trastornos cartilago",9),
    ("N00","Sindrome nefritico agudo",10), ("N03","Sindrome nefritico cronico",10),
    ("N04","Sindrome nefrotico",10), ("N10","Nefritis tubulointersticial aguda",10),
    ("N11","Nefritis tubulointersticial cronica",10), ("N13","Uropatia obstructiva",10),
    ("N17","Insuficiencia renal aguda",10), ("N18","ERC (enfermedad renal cronica)",10),
    ("N19","Insuficiencia renal NE",10), ("N20","Calculo renal/ureteral",10),
    ("N23","Colico renal NE",10), ("N28","Otros trastornos rinon",10),
    ("N30","Cistitis",10), ("N34","Uretritis",10),
    ("N35","Estenosis uretral",10), ("N39","Otros trastornos urinarios",10),
    ("N40","HPB (hiperplasia prostatica)",10), ("N41","Prostatitis",10),
    ("N43","Hidrocele",10), ("N44","Torsion testicular",10),
    ("N45","Orquitis/epididimitis",10), ("N47","Fimosis/parafimosis",10),
    ("N60","Displasias mamarias benignas",10), ("N61","Trastornos inflamatorios mama",10),
    ("N63","Nodulo mamario NE",10), ("N64","Otros trastornos mama",10),
    ("N70","Salpingitis/ooforitis",10), ("N71","Enfermedad inflamatoria uterina",10),
    ("N72","Enfermedad inflamatoria cuello",10), ("N73","Otras EIP",10),
    ("N76","Otras inflamaciones vaginales",10), ("N80","Endometriosis",10),
    ("N81","Prolapso genital femenino",10), ("N83","Trastornos no inflamatorios ovario",10),
    ("N85","Otros trastornos utero",10), ("N87","Displasia cervical",10),
    ("N91","Menstruacion ausente/escasa",10), ("N92","Menstruacion excesiva",10),
    ("N94","Dolor y otras afecciones genitales",10), ("N95","Trastornos menopausicos",10),
    ("N97","Infertilidad femenina",10),
    ("H00","Orzuelo/chalazion",11), ("H01","Otras inflamaciones parpado",11),
    ("H04","Trastornos aparato lagrimal",11), ("H10","Conjuntivitis",11),
    ("H15","Trastornos esclera",11), ("H16","Queratitis",11),
    ("H18","Otros trastornos cornea",11), ("H20","Iridociclitis (uveitis)",11),
    ("H25","Catarata senil",11), ("H26","Otras cataratas",11),
    ("H33","Desprendimiento retina",11), ("H34","Oclusion vascular retiniana",11),
    ("H35","Otros trastornos retina",11), ("H40","Glaucoma",11),
    ("H43","Trastornos vitreo",11), ("H44","Trastornos globo ocular",11),
    ("H46","Neuritis optica",11), ("H47","Otros trastornos nervio optico",11),
    ("H50","Estrabismo",11), ("H52","Trastornos refraccion",11),
    ("H53","Trastornos vision",11), ("H54","Ceguera/baja vision",11),
    ("H60","Otitis externa",12), ("H61","Otros trastornos oido externo",12),
    ("H65","Otitis media no supurativa",12), ("H66","Otitis media supurativa",12),
    ("H68","Trompa de Eustaquio",12), ("H70","Mastoiditis",12),
    ("H72","Perforacion timpano",12), ("H80","Otosclerosis",12),
    ("H81","Trastornos equilibrio",12), ("H90","Hipoacusia conductiva/neurosensorial",12),
    ("H91","Otras hipoacusias",12), ("H92","Otalgia/secrecion",12),
    ("O00","Embarazo ectopico",13), ("O03","Aborto espontaneo",13),
    ("O04","Aborto medico",13), ("O06","Aborto NE",13),
    ("O08","Complicaciones post-aborto",13), ("O10","Hipertension preexistente",13),
    ("O11","Preeclampsia sobre HTA",13), ("O13","Hipertension gestacional",13),
    ("O14","Preeclampsia",13), ("O15","Eclampsia",13),
    ("O20","Hemorragia temprana embarazo",13), ("O21","Hiperemesis gravidica",13),
    ("O23","Infecciones urinarias embarazo",13), ("O24","Diabetes gestacional",13),
    ("O26","Atencion materna otros problemas",13), ("O30","Embarazo multiple",13),
    ("O32","Presentacion anormal feto",13), ("O34","Cuidados por anomalia pelvica",13),
    ("O36","Atencion por otros problemas fetales",13), ("O40","Polihidramnios",13),
    ("O41","Otros trastornos liquido amniotico",13), ("O42","RPM (ruptura prematura membranas)",13),
    ("O44","Placenta previa",13), ("O45","DPPNI",13),
    ("O46","Hemorragia anteparto NE",13), ("O48","Embarazo prolongado",13),
    ("O60","Parto prematuro",13), ("O61","Fallo induccion parto",13),
    ("O62","Anomalias contracciones",13), ("O63","Trabajo parto prolongado",13),
    ("O64","Obstruccion por posicion fetal",13), ("O65","Obstruccion por pelvis materna",13),
    ("O66","Otra obstruccion parto",13), ("O68","Sufrimiento fetal",13),
    ("O70","Desgarro perineal parto",13), ("O71","Otra trauma obstetrico",13),
    ("O72","Hemorragia postparto",13), ("O73","Retencion placenta/membranas",13),
    ("O80","Parto unico espontaneo",13), ("O81","Parto con forceps",13),
    ("O82","Parto por cesarea",13), ("O85","Sepsis puerperal",13),
    ("O86","Otras infecciones puerperales",13), ("O90","Complicaciones puerperio",13),
    ("O91","Trastornos mamarios puerperio",13), ("O92","Otros trastornos lactancia",13),
    ("O94","Secuelas complicacion embarazo",13), ("O98","Enf maternas claseables obstetricia",13),
    ("O99","Otras enf maternas complicando embarazo",13),
    ("P00","Feto/neonato afectado por enf materna",14), ("P01","Feto afectado por complicacion embarazo",14),
    ("P02","Feto afectado por complicacion placenta",14), ("P03","Feto afectado por complicacion parto",14),
    ("P05","Retraso crecimiento fetal/desnutricion",14), ("P07","Trastornos relacionados gestacion corta",14),
    ("P08","Trastornos relacionados embarazo prolongado",14), ("P10","Trauma nacimiento intracraneal",14),
    ("P11","Otro trauma nacimiento SNC",14), ("P12","Trauma nacimiento cuero cabelludo",14),
    ("P15","Otros traumas nacimiento",14), ("P20","Hipoxia intrauterina",14),
    ("P21","Asfixia al nacer",14), ("P22","Dificultad respiratoria neonatal",14),
    ("P23","Neumonia congenita",14), ("P24","Sindrome aspiracion neonatal",14),
    ("P25","Enfisema intersticial neonatal",14), ("P26","Hemorragia pulmonar neonatal",14),
    ("P27","Enf respiratoria cronica perinatal",14), ("P28","Otros problemas respiratorios neonatales",14),
    ("P29","Trastornos cardiovasculares perinatales",14), ("P35","Enf virales congenitas",14),
    ("P36","Sepsis bacteriana neonatal",14), ("P37","Otras enf infecciosas perinatales",14),
    ("P38","Onfalitis del recien nacido",14), ("P39","Otras infecciones perinatales",14),
    ("P50","Perdida sangre fetal",14), ("P52","Hemorragia intracraneal fetal/neonatal",14),
    ("P55","Enf hemolitica del feto/neonato",14), ("P57","Kernicterus",14),
    ("P58","Ictericia neonatal por hemolisis",14), ("P59","Ictericia neonatal otras causas",14),
    ("P61","Otros trastornos hematologicos perinatales",14), ("P70","Trastornos transitorios metabolismo neonatal",14),
    ("P74","Otros trastornos electroliticos neonatales",14), ("P76","Otra obstruccion intestinal neonatal",14),
    ("P78","Otros trastornos digestivos perinatales",14), ("P80","Hipotermia neonatal",14),
    ("P81","Otros trastornos regulacion temperatura",14), ("P83","Otros trastornos piel neonatal",14),
    ("P90","Convulsiones neonatales",14), ("P91","Otros trastornos SNC neonatal",14),
    ("P92","Problemas alimentacion recien nacido",14), ("P94","Trastornos tono muscular neonatal",14),
    ("P95","Muerte fetal NE",14), ("P96","Otros trastornos perinatales",14),
    ("R00","Anormalidades del latido cardiaco",15), ("R01","Soplos/ruidos cardiacos",15),
    ("R02","Gangrena NE",15), ("R03","Lectura PA anormal",15),
    ("R04","Hemorragia vias respiratorias",15), ("R05","Tos",15),
    ("R06","Anormalidades respiracion",15), ("R07","Dolor garganta/pecho",15),
    ("R09","Otros sintomas respiratorios",15), ("R10","Dolor abdominal/pelvico",15),
    ("R11","Nausea/vomito",15), ("R12","Acidez",15),
    ("R13","Disfagia",15), ("R14","Flatulencia",15),
    ("R15","Incontinencia fecal",15), ("R16","Hepatomegalia/esplenomegalia",15),
    ("R17","Ictericia NE",15), ("R18","Ascitis",15),
    ("R19","Otros sintomas digestivos",15), ("R20","Trastornos sensibilidad piel",15),
    ("R21","Erupcion cutanea NE",15), ("R22","Tumoracion localizada",15),
    ("R23","Otros cambios piel",15), ("R25","Movimientos involuntarios",15),
    ("R26","Anormalidades marcha",15), ("R27","Falta coordinacion",15),
    ("R29","Otros sintomas neurologicos",15), ("R30","Dolor miccional",15),
    ("R31","Hematuria NE",15), ("R32","Incontinencia urinaria NE",15),
    ("R33","Retencion urinaria",15), ("R34","Anuria/oliguria",15),
    ("R35","Poliuria",15), ("R36","Secrecion uretral",15),
    ("R39","Otros sintomas urinarios",15), ("R40","Somnolencia/estupor/coma",15),
    ("R41","Otros sintomas cognicion",15), ("R42","Mareo/inestabilidad",15),
    ("R43","Trastornos olfato/gusto",15), ("R44","Otros sintomas sensopercepcion",15),
    ("R45","Sintomas emocionales",15), ("R46","Sintomas apariencia/conducta",15),
    ("R47","Trastornos habla NE",15), ("R48","Trastornos reconocimiento",15),
    ("R49","Trastornos voz",15), ("R50","Fiebre de origen desconocido",15),
    ("R51","Cefalea",15), ("R52","Dolor agudo/cronico NE",15),
    ("R53","Malestar/fatiga",15), ("R54","Senilidad",15),
    ("R55","Sincope/colapso",15), ("R56","Convulsiones NE",15),
    ("R57","Shock NE",15), ("R58","Hemorragia NE",15),
    ("R59","Adenomegalia",15), ("R60","Edema NE",15),
    ("R61","Hiperhidrosis",15), ("R62","Falta desarrollo esperado",15),
    ("R63","Sintomas alimentacion",15), ("R64","Caquexia",15),
    ("R68","Otros sintomas generales",15), ("R69","Causa morbida desconocida",15),
    ("R70","Velocidad sedimentacion elevada",15), ("R71","Anormalidad eritrocitos",15),
    ("R72","Anormalidad leucocitos",15), ("R73","Glucemia elevada",15),
    ("R74","Anormalidad enzimas hepaticas",15), ("R75","Hallazgo serologico VIH",15),
    ("R76","Otros hallazgos immunologicos",15), ("R77","Otras anormalidades proteinas",15),
    ("R78","Presencia de drogas en sangre",15), ("R79","Otras anormalidades quimicas",15),
    ("R80","Proteinuria aislada",15), ("R81","Glucosuria",15),
    ("R82","Otras anormalidades orina",15), ("R83","Anormalidad LCR",15),
    ("R84","Anormalidad organos respiratorios",15), ("R85","Anormalidad organos digestivos",15),
    ("R86","Anormalidad organos genitales masculinos",15), ("R87","Anormalidad organos genitales femeninos",15),
    ("R89","Anormalidad otros organos",15), ("R90","Anormalidad SNC en diagnostico",15),
    ("R91","Anormalidad pulmonar en diagnostico",15), ("R92","Anormalidad mama en diagnostico",15),
    ("R93","Anormalidad otros organos en diagnostico",15), ("R94","Anormalidad pruebas funcionales",15),
    ("R95","SMSL (muerte subita infantil)",15), ("R96","Otra muerte subita",15),
    ("R98","Muerte sin asistencia",15), ("R99","Causa muerte desconocida",15),
    ("S00","Trauma superficial cabeza",16),  ("S01","Herida abierta cabeza",16),
    ("S02","Fractura huesos craneo/cara",16), ("S06","Trauma intracraneal",16),
    ("S09","Otros traumas cabeza",16), ("S10","Trauma superficial cuello",16),
    ("S11","Herida abierta cuello",16), ("S12","Fractura cuello",16),
    ("S13","Luxacion cuello",16), ("S20","Trauma superficial torax",16),
    ("S21","Herida abierta torax",16), ("S22","Fractura costilla/esternon/columna",16),
    ("S24","Trauma medula espinal toracica",16), ("S27","Trauma otros organos intratoracicos",16),
    ("S30","Trauma superficial abdomen",16), ("S31","Herida abierta abdomen",16),
    ("S32","Fractura columna lumbosacra",16), ("S36","Trauma organos intraabdominales",16),
    ("S37","Trauma organos urinarios/pelvicos",16), ("S40","Trauma superficial hombro/brazo",16),
    ("S42","Fractura humero",16), ("S43","Luxacion hombro",16),
    ("S44","Trauma nervios hombro/brazo",16), ("S46","Trauma musculo hombro/brazo",16),
    ("S50","Trauma superficial antebrazo",16), ("S52","Fractura antebrazo",16),
    ("S53","Luxacion codo",16), ("S60","Trauma superficial muneca/mano",16),
    ("S61","Herida abierta muneca/mano",16), ("S62","Fractura muneca/mano",16),
    ("S63","Luxacion muneca/mano",16), ("S70","Trauma superficial cadera/muslo",16),
    ("S71","Herida abierta cadera/muslo",16), ("S72","Fractura femur",16),
    ("S73","Luxacion cadera",16), ("S80","Trauma superficial pierna",16),
    ("S81","Herida abierta pierna",16), ("S82","Fractura pierna (tib/perone)",16),
    ("S83","Luxacion rodilla",16), ("S86","Trauma musculo pierna",16),
    ("S90","Trauma superficial tobillo/pie",16), ("S91","Herida abierta tobillo/pie",16),
    ("S92","Fractura pie",16), ("S93","Luxacion tobillo/pie",16),
    ("T00","Traumas superficiales multiples",16), ("T01","Heridas abiertas multiples",16),
    ("T02","Fracturas multiples",16), ("T08","Fractura columna vertebral NE",16),
    ("T09","Otros traumas columna NE",16), ("T14","Trauma region corporal NE",16),
    ("T15","Cuerpo extraño ojo",16), ("T16","Cuerpo extraño oido",16),
    ("T17","Cuerpo extraño respiratorio",16), ("T18","Cuerpo extraño digestivo",16),
    ("T20","Quemadura cabeza/cuello",16), ("T21","Quemadura torax",16),
    ("T22","Quemadura hombro/MS",16), ("T23","Quemadura muneca/mano",16),
    ("T24","Quemadura cadera/MI",16), ("T25","Quemadura tobillo/pie",16),
    ("T29","Quemaduras multiples",16), ("T30","Quemadura NE",16),
    ("T31","Quemadura segun superficie",16), ("T32","Corrosion segun superficie",16),
    ("T40","Intoxicacion por narcoticos",16), ("T42","Intoxicacion por anticonv./sedantes",16),
    ("T43","Intoxicacion por psicotropicos",16), ("T44","Intoxicacion por autonomos",16),
    ("T45","Intoxicacion por sistemicos",16), ("T46","Intoxicacion por cardiovasculares",16),
    ("T47","Intoxicacion por digestivos",16), ("T48","Intoxicacion por topicos",16),
    ("T49","Intoxicacion por topicos dermatologicos",16), ("T50","Intoxicacion por diureticos",16),
    ("T51","Efecto toxico alcohol",16), ("T58","Efecto toxico monoxido carbono",16),
    ("T65","Efecto toxico otras sustancias",16), ("T66","Efecto radiacion NE",16),
    ("T67","Efectos calor/luz",16), ("T68","Hipotermia",16),
    ("T69","Otros efectos temperatura reducida",16), ("T70","Efectos presion atmosferica",16),
    ("T71","Asfixia",16), ("T74","Maltrato (abusos)",16),
    ("T75","Efectos otras causas externas",16), ("T78","Efectos adversos NE",16),
    ("T79","Complicaciones tempranas trauma",16), ("T80","Complicaciones infusion/transfusion",16),
    ("T81","Complicaciones procedimientos NE",16), ("T82","Complicaciones protesis cardiaca",16),
    ("T83","Complicaciones protesis urinaria",16), ("T84","Complicaciones protesis ortopedica",16),
    ("T85","Complicaciones otros implantes",16), ("T86","Fracaso/ rechazo trasplante",16),
    ("T87","Complicaciones reimplante/amputacion",16), ("T88","Otras complicaciones quirurgicas",16),
    ("T90","Secuelas trauma cabeza",16), ("T91","Secuelas trauma cuello/torax",16),
    ("T92","Secuelas trauma MS",16), ("T93","Secuelas trauma MI",16),
    ("T94","Secuelas trauma multiple/NE",16), ("T95","Secuelas quemaduras",16),
    ("T98","Secuelas otras causas externas",16),
]

def _build_catalogo():
    """Convierte _CIE10_RAW en lista de dicts con categoria expandida."""
    return [
        {"codigo": c, "descripcion": d, "categoria": CATEGORIAS[cat_idx]}
        for c, d, cat_idx in _CIE10_RAW
    ]

def _build_indice():
    """Construye indice {codigo: (descripcion, categoria)} para busqueda O(1)."""
    return {c: (d, CATEGORIAS[cat_idx]) for c, d, cat_idx in _CIE10_RAW}

CIE10_CATALOGO = _build_catalogo()
CIE10_INDICE = _build_indice()

def buscar_cie10(query: str, max_results: int = 20) -> list:
    """Busqueda case-insensitive por codigo o descripcion."""
    q = query.strip().lower()
    if not q:
        return []
    results = []
    for entry in CIE10_CATALOGO:
        if q in entry["codigo"].lower() or q in entry["descripcion"].lower():
            results.append(entry)
            if len(results) >= max_results:
                break
    return results

def obtener_cie10(codigo: str) -> dict | None:
    """Retorna entrada del catalogo por codigo exacto."""
    res = CIE10_INDICE.get(codigo.upper().strip())
    if res:
        return {"codigo": codigo.upper().strip(), "descripcion": res[0], "categoria": res[1]}
    return None

# CIE-11 mapeo minimo (codigos mas relevantes)
CIE11_MAPEO = {
    "A09": "MA00", "A15": "MA05", "A41": "MA15", "A90": "MA60",
    "B01": "MA70", "B02": "MA71", "B15": "MA85", "B16": "MA86",
    "B18": "MA87", "B20": "MA90", "B24": "MA91", "B37": "MA99",
    "B57": "MB10", "B58": "MB11", "B86": "MB15", "C50": "MC50",
    "C61": "MC61", "C34": "MC34", "C18": "MC18", "C16": "MC16",
    "D50": "MD50", "D64": "MD64", "E10": "ME10", "E11": "ME11",
    "E66": "ME66", "E78": "ME78", "F20": "MF20", "F31": "MF31",
    "F32": "MF32", "F41": "MF41", "F84": "MF84", "F90": "MF90",
    "G40": "MG40", "G43": "MG43", "I10": "MI10", "I21": "MI21",
    "I48": "MI48", "I50": "MI50", "I64": "MI64", "J00": "MJ00",
    "J03": "MJ03", "J15": "MJ15", "J18": "MJ18", "J44": "MJ44",
    "J45": "MJ45", "K21": "MK21", "K29": "MK29", "K35": "MK35",
    "K40": "MK40", "K74": "MK74", "K80": "MK80", "L03": "ML03",
    "L40": "ML40", "L89": "ML89", "M05": "MM05", "M10": "MM10",
    "M17": "MM17", "M54": "MM54", "M81": "MM81", "N18": "MN18",
    "N20": "MN20", "N30": "MN30", "N40": "MN40", "N80": "MN80",
    "O14": "MO14", "O24": "MO24", "O80": "MO80", "O82": "MO82",
    "P07": "MP07", "P22": "MP22", "R05": "MR05", "R10": "MR10",
    "R11": "MR11", "R50": "MR50", "R51": "MR51", "R55": "MR55",
    "S06": "MS06", "S52": "MS52", "S72": "MS72", "S82": "MS82",
}

def mapear_a_cie11(codigo_cie10: str) -> str | None:
    """Retorna codigo CIE-11 equivalente o None."""
    return CIE11_MAPEO.get(codigo_cie10.upper().strip())
