# HTML/CSS de la landing pre-login (publicidad). Mantener contenido comercial aca para no inflar main.py.


def obtener_html_landing_publicidad(logo_html: str) -> str:
    """Retorna el bloque completo <style> + markup para st.markdown(..., unsafe_allow_html=True)."""
    return "".join(
        [
            "<style>",
            "@import url('https://fonts.googleapis.com/css2?family=Fraunces:ital,opsz,wght@0,9..144,600;0,9..144,700;0,9..144,800;1,9..144,600&family=Plus+Jakarta+Sans:wght@400;500;600;700;800&display=swap');",
            ":root {",
            "  --lp-void: #04070d;",
            "  --lp-ink: #e8eef7;",
            "  --lp-mute: #8b9cb3;",
            "  --lp-line: rgba(20, 184, 166, 0.22);",
            "  --lp-line-soft: rgba(148, 163, 184, 0.12);",
            "  --lp-accent: #14b8a6;",
            "  --lp-accent-deep: #0d9488;",
            "  --lp-blue: #3b82f6;",
            "  --lp-card: rgba(12, 18, 32, 0.72);",
            "  --lp-glow: rgba(20, 184, 166, 0.12);",
            "}",
            ".mc-lp { font-family: 'Plus Jakarta Sans', system-ui, sans-serif; color: var(--lp-ink); position: relative; isolation: isolate; overflow-x: clip; }",
            ".mc-lp * { box-sizing: border-box; }",
            ".mc-lp-bg { position: fixed; inset: 0; z-index: -2; background: var(--lp-void); }",
            ".mc-lp-bg::before { content: ''; position: absolute; inset: 0; background:",
            "  radial-gradient(ellipse 100% 70% at 50% -30%, var(--lp-glow), transparent 55%),",
            "  radial-gradient(ellipse 60% 50% at 100% 20%, rgba(59, 130, 246, 0.08), transparent 50%),",
            "  radial-gradient(ellipse 50% 40% at 0% 80%, rgba(20, 184, 166, 0.06), transparent 45%); }",
            ".mc-lp-bg::after { content: ''; position: absolute; inset: 0; opacity: 0.35;",
            "  background-image: linear-gradient(rgba(148,163,184,0.04) 1px, transparent 1px),",
            "    linear-gradient(90deg, rgba(148,163,184,0.04) 1px, transparent 1px);",
            "  background-size: 56px 56px; mask-image: radial-gradient(ellipse 85% 75% at 50% 40%, black, transparent); }",
            ".mc-lp-inner { max-width: 1180px; margin: 0 auto; padding: 48px 22px 36px; }",
            ".mc-lp-header { display: flex; flex-wrap: wrap; align-items: center; justify-content: space-between; gap: 20px; margin-bottom: 48px; padding-bottom: 28px; border-bottom: 1px solid var(--lp-line-soft); }",
            ".mc-lp-brand { display: flex; align-items: center; gap: 20px; }",
            ".mc-lp-logo-wrap { padding: 14px 18px; border-radius: 20px; background: linear-gradient(165deg, rgba(255,255,255,0.98), rgba(241,245,249,0.92)); box-shadow: 0 20px 50px rgba(0,0,0,0.35), 0 0 0 1px rgba(255,255,255,0.5) inset; }",
            ".mc-lp-brand-text { display: flex; flex-direction: column; gap: 4px; }",
            ".mc-lp-brand-name { font-family: 'Fraunces', Georgia, serif; font-size: 1.55rem; font-weight: 700; letter-spacing: -0.02em; color: #f8fafc; margin: 0; line-height: 1.15; }",
            ".mc-lp-brand-tag { font-size: 0.72rem; font-weight: 800; letter-spacing: 0.2em; text-transform: uppercase; color: var(--lp-accent); }",
            ".mc-lp-header-badge { font-size: 0.78rem; font-weight: 700; color: var(--lp-mute); padding: 10px 16px; border-radius: 999px; border: 1px solid var(--lp-line-soft); background: rgba(8, 12, 22, 0.6); }",
            ".mc-lp-hero { display: grid; grid-template-columns: 1.15fr 0.85fr; gap: 40px; align-items: start; margin-bottom: 52px; }",
            "@media (max-width: 920px) { .mc-lp-hero { grid-template-columns: 1fr; gap: 32px; } }",
            ".mc-lp-hero-copy { position: relative; padding-left: 22px; }",
            ".mc-lp-hero-copy::before { content: ''; position: absolute; left: 0; top: 6px; bottom: 6px; width: 3px; border-radius: 3px;",
            "  background: linear-gradient(180deg, var(--lp-accent), var(--lp-blue)); }",
            ".mc-lp-kicker { font-size: 0.76rem; font-weight: 800; letter-spacing: 0.18em; text-transform: uppercase; color: var(--lp-accent); margin: 0 0 14px; }",
            ".mc-lp-h1 { font-family: 'Fraunces', Georgia, serif; font-size: clamp(2.1rem, 5.2vw, 3.35rem); font-weight: 800; line-height: 1.08; letter-spacing: -0.03em; margin: 0 0 20px; color: #f8fafc; }",
            ".mc-lp-h1 em { font-style: italic; font-weight: 700; background: linear-gradient(120deg, #5eead4 0%, #7dd3fc 45%, #93c5fd 100%); -webkit-background-clip: text; -webkit-text-fill-color: transparent; background-clip: text; }",
            ".mc-lp-lead { font-size: 1.12rem; line-height: 1.75; color: var(--lp-mute); margin: 0 0 26px; max-width: 36rem; font-weight: 500; }",
            ".mc-lp-pills { display: flex; flex-wrap: wrap; gap: 10px; }",
            ".mc-lp-pill { font-size: 0.8rem; font-weight: 700; padding: 8px 14px; border-radius: 999px; border: 1px solid var(--lp-line-soft); color: #cbd5e1; background: rgba(10, 16, 28, 0.75); }",
            ".mc-lp-pill strong { color: var(--lp-accent); font-weight: 800; }",
            ".mc-lp-showcase { position: relative; border-radius: 24px; padding: 1px; background: linear-gradient(145deg, rgba(20,184,166,0.35), rgba(59,130,246,0.2) 50%, rgba(20,184,166,0.08)); box-shadow: 0 28px 60px rgba(0,0,0,0.45); }",
            ".mc-lp-showcase-in { border-radius: 23px; background: linear-gradient(165deg, rgba(14, 22, 38, 0.96) 0%, rgba(6, 10, 18, 0.98) 100%); padding: 22px 22px 20px; border: 1px solid rgba(148,163,184,0.08); }",
            ".mc-lp-sc-title { font-size: 0.7rem; font-weight: 800; letter-spacing: 0.14em; text-transform: uppercase; color: var(--lp-mute); margin: 0 0 16px; }",
            ".mc-lp-sc-rows { display: flex; flex-direction: column; gap: 12px; }",
            ".mc-lp-sc-row { display: flex; align-items: center; gap: 14px; padding: 14px 16px; border-radius: 14px; background: rgba(20, 28, 45, 0.85); border: 1px solid var(--lp-line-soft); }",
            ".mc-lp-sc-dot { width: 10px; height: 10px; border-radius: 50%; flex-shrink: 0; }",
            ".mc-lp-sc-dot.a { background: var(--lp-accent); box-shadow: 0 0 14px rgba(20,184,166,0.5); }",
            ".mc-lp-sc-dot.b { background: var(--lp-blue); box-shadow: 0 0 14px rgba(59,130,246,0.4); }",
            ".mc-lp-sc-dot.c { background: #fbbf24; box-shadow: 0 0 12px rgba(251,191,36,0.35); }",
            ".mc-lp-sc-txt { flex: 1; min-width: 0; }",
            ".mc-lp-sc-txt b { display: block; font-size: 0.92rem; color: #f1f5f9; margin-bottom: 2px; }",
            ".mc-lp-sc-txt span { font-size: 0.8rem; color: var(--lp-mute); }",
            ".mc-lp-stats { display: grid; grid-template-columns: repeat(4, 1fr); gap: 14px; margin-bottom: 48px; }",
            "@media (max-width: 720px) { .mc-lp-stats { grid-template-columns: repeat(2, 1fr); } }",
            ".mc-lp-stat { text-align: center; padding: 20px 14px; border-radius: 18px; border: 1px solid var(--lp-line-soft); background: var(--lp-card); }",
            ".mc-lp-stat-val { font-family: 'Fraunces', Georgia, serif; font-size: 1.65rem; font-weight: 700; color: #f8fafc; line-height: 1.1; }",
            ".mc-lp-stat-lbl { font-size: 0.72rem; font-weight: 700; text-transform: uppercase; letter-spacing: 0.12em; color: var(--lp-mute); margin-top: 8px; }",
            ".mc-lp-section-h { font-family: 'Fraunces', Georgia, serif; font-size: 1.65rem; font-weight: 700; margin: 0 0 8px; color: #f8fafc; letter-spacing: -0.02em; }",
            ".mc-lp-section-sub { font-size: 0.98rem; color: var(--lp-mute); margin: 0 0 28px; max-width: 42rem; line-height: 1.65; }",
            ".mc-lp-bento { display: grid; grid-template-columns: repeat(12, 1fr); gap: 16px; margin-bottom: 48px; }",
            ".mc-lp-b1 { grid-column: span 7; min-height: 200px; }",
            ".mc-lp-b2 { grid-column: span 5; min-height: 200px; }",
            ".mc-lp-b3 { grid-column: span 4; }",
            ".mc-lp-b4 { grid-column: span 4; }",
            ".mc-lp-b5 { grid-column: span 4; }",
            "@media (max-width: 900px) { .mc-lp-b1, .mc-lp-b2, .mc-lp-b3, .mc-lp-b4, .mc-lp-b5 { grid-column: span 12; min-height: auto; } }",
            ".mc-lp-cell { height: 100%; border-radius: 22px; padding: 26px 24px; border: 1px solid var(--lp-line-soft); background: var(--lp-card); box-shadow: 0 16px 40px rgba(0,0,0,0.2); transition: border-color 0.25s ease, transform 0.25s ease; }",
            ".mc-lp-cell:hover { border-color: var(--lp-line); transform: translateY(-3px); }",
            ".mc-lp-cell h4 { margin: 0 0 10px; font-size: 1.08rem; font-weight: 800; color: #f8fafc; }",
            ".mc-lp-cell p { margin: 0; font-size: 0.94rem; line-height: 1.65; color: var(--lp-mute); }",
            ".mc-lp-cell .mc-lp-ico { font-size: 1.75rem; margin-bottom: 14px; line-height: 1; }",
            ".mc-lp-split { display: grid; grid-template-columns: 1fr 1fr; gap: 20px; margin-bottom: 48px; }",
            "@media (max-width: 800px) { .mc-lp-split { grid-template-columns: 1fr; } }",
            ".mc-lp-panel { border-radius: 24px; padding: 28px 26px; border: 1px solid var(--lp-line-soft); background: linear-gradient(160deg, rgba(16, 26, 44, 0.9), rgba(8, 12, 22, 0.95)); }",
            ".mc-lp-panel h3 { font-family: 'Fraunces', Georgia, serif; font-size: 1.45rem; margin: 0 0 12px; color: #f8fafc; }",
            ".mc-lp-panel p { margin: 0; color: var(--lp-mute); line-height: 1.7; font-size: 0.98rem; }",
            ".mc-lp-checks { display: flex; flex-direction: column; gap: 10px; margin-top: 18px; }",
            ".mc-lp-check { font-size: 0.9rem; color: #cbd5e1; padding: 12px 14px; border-radius: 12px; border: 1px solid var(--lp-line-soft); background: rgba(8, 14, 26, 0.5); }",
            ".mc-lp-check::before { content: '✓'; color: var(--lp-accent); font-weight: 900; margin-right: 10px; }",
            ".mc-lp-grid8 { display: grid; grid-template-columns: repeat(auto-fill, minmax(240px, 1fr)); gap: 16px; margin-bottom: 44px; }",
            ".mc-lp-mini { border-radius: 18px; padding: 22px 20px; border: 1px solid var(--lp-line-soft); background: rgba(10, 16, 28, 0.65); transition: 0.2s; }",
            ".mc-lp-mini:hover { border-color: rgba(20, 184, 166, 0.35); }",
            ".mc-lp-mini .t { font-weight: 800; font-size: 1rem; color: #f1f5f9; margin-bottom: 8px; }",
            ".mc-lp-mini .d { font-size: 0.88rem; color: var(--lp-mute); line-height: 1.55; margin: 0; }",
            ".mc-lp-band { border-radius: 26px; padding: 36px 32px; margin-bottom: 44px; border: 1px solid var(--lp-line); background: linear-gradient(120deg, rgba(13, 148, 136, 0.12), rgba(37, 99, 235, 0.08)); }",
            ".mc-lp-band h3 { font-family: 'Fraunces', Georgia, serif; font-size: 1.5rem; margin: 0 0 20px; color: #f8fafc; }",
            ".mc-lp-benefits { display: grid; grid-template-columns: repeat(auto-fit, minmax(200px, 1fr)); gap: 14px; }",
            ".mc-lp-ben { padding: 18px 16px; border-radius: 16px; border: 1px solid var(--lp-line-soft); background: rgba(6, 10, 18, 0.55); }",
            ".mc-lp-ben h5 { margin: 0 0 6px; font-size: 0.92rem; font-weight: 800; color: #e2e8f0; }",
            ".mc-lp-ben p { margin: 0; font-size: 0.85rem; color: var(--lp-mute); line-height: 1.55; }",
            ".mc-lp-close { display: grid; grid-template-columns: 1.2fr 0.8fr; gap: 18px; margin-bottom: 44px; }",
            "@media (max-width: 800px) { .mc-lp-close { grid-template-columns: 1fr; } }",
            ".mc-lp-close-box { border-radius: 22px; padding: 26px 24px; border: 1px solid rgba(20, 184, 166, 0.25); background: linear-gradient(145deg, rgba(13, 148, 136, 0.15), rgba(37, 99, 235, 0.12)); }",
            ".mc-lp-close-box h3 { font-family: 'Fraunces', Georgia, serif; font-size: 1.35rem; margin: 0 0 10px; color: #f8fafc; }",
            ".mc-lp-close-box p { margin: 0; color: #cbd5e1; line-height: 1.7; font-size: 0.95rem; }",
            ".mc-lp-contact { border-radius: 28px; padding: 44px 32px; text-align: center; border: 1px solid var(--lp-line); background: linear-gradient(180deg, rgba(12, 20, 36, 0.95), rgba(4, 7, 13, 0.98)); box-shadow: 0 28px 70px rgba(0,0,0,0.4); position: relative; overflow: hidden; }",
            ".mc-lp-contact::before { content: ''; position: absolute; width: 320px; height: 320px; right: -100px; top: -120px; background: radial-gradient(circle, var(--lp-glow), transparent 70%); pointer-events: none; }",
            ".mc-lp-contact h3 { font-family: 'Fraunces', Georgia, serif; font-size: clamp(1.5rem, 3vw, 2rem); margin: 0 0 10px; color: #f8fafc; position: relative; }",
            ".mc-lp-contact .sub { color: var(--lp-mute); font-size: 1.05rem; margin: 0 0 28px; position: relative; }",
            ".mc-lp-cgrid { display: flex; flex-wrap: wrap; justify-content: center; gap: 22px; position: relative; }",
            ".mc-lp-card { flex: 1; min-width: 260px; max-width: 400px; padding: 28px 24px; border-radius: 20px; border: 1px solid var(--lp-line-soft); background: rgba(8, 14, 26, 0.75); text-align: center; transition: 0.25s; }",
            ".mc-lp-card:hover { border-color: var(--lp-line); transform: translateY(-4px); }",
            ".mc-lp-card .nm { font-size: 1.25rem; font-weight: 800; color: #fff; margin: 0 0 6px; }",
            ".mc-lp-card .rl { font-size: 0.75rem; font-weight: 800; letter-spacing: 0.14em; text-transform: uppercase; color: var(--lp-accent); margin: 0 0 22px; }",
            ".mc-lp-btns { display: flex; gap: 12px; justify-content: center; flex-wrap: wrap; }",
            ".mc-lp-btns a { display: inline-flex; align-items: center; justify-content: center; padding: 13px 22px; border-radius: 12px; font-weight: 800; font-size: 0.88rem; text-decoration: none !important; color: #fff !important; transition: 0.2s; }",
            ".mc-lp-btns a:focus-visible { outline: 3px solid #5eead4; outline-offset: 4px; }",
            ".mc-lp-wa { background: linear-gradient(135deg, #16a34a, #15803d); box-shadow: 0 6px 20px rgba(22,163,74,0.35); }",
            ".mc-lp-wa:hover { filter: brightness(1.1); transform: translateY(-2px); }",
            ".mc-lp-em { background: linear-gradient(135deg, #2563eb, #1d4ed8); box-shadow: 0 6px 20px rgba(37,99,235,0.3); }",
            ".mc-lp-em:hover { filter: brightness(1.08); transform: translateY(-2px); }",
            ".mc-lp-trust { display: flex; flex-wrap: wrap; justify-content: center; gap: 10px 18px; margin: 0 0 40px; padding: 16px 20px; border-radius: 16px; border: 1px solid var(--lp-line-soft); background: rgba(6, 10, 18, 0.45); }",
            ".mc-lp-trust span { font-size: 0.78rem; font-weight: 700; color: #94a3b8; letter-spacing: 0.06em; text-transform: uppercase; }",
            ".mc-lp-trust span strong { color: var(--lp-accent); font-weight: 800; margin-right: 6px; }",
            ".mc-lp-cta-wrap { margin-top: 36px; padding: 28px 20px 8px; text-align: center; }",
            ".mc-lp-cta-wrap p { margin: 0 0 6px; font-size: 0.88rem; font-weight: 600; color: var(--lp-mute); letter-spacing: 0.04em; text-transform: uppercase; }",
            ".mc-lp-cta-wrap .mc-lp-cta-sub { text-transform: none; letter-spacing: 0; font-weight: 500; font-size: 0.92rem; color: #94a3b8; max-width: 28rem; margin: 0 auto 8px; line-height: 1.5; }",
            "@media (prefers-reduced-motion: reduce) { .mc-lp-cell:hover, .mc-lp-mini:hover, .mc-lp-card:hover, .mc-lp-btns a:hover { transform: none !important; } .mc-lp-btns a, .mc-lp-cell { transition: none !important; } }",
            "@media (max-width: 768px) { .mc-lp-inner { padding: 36px 16px 28px; } .mc-lp-header { margin-bottom: 36px; padding-bottom: 22px; }",
            "  .mc-lp-grid8 { display: flex; overflow-x: auto; gap: 14px; padding-bottom: 10px; scroll-snap-type: x proximity; -webkit-overflow-scrolling: touch; }",
            "  .mc-lp-mini { flex: 0 0 82%; min-width: 260px; scroll-snap-align: start; } }",
            "</style>",
            "<div class='mc-lp'><div class='mc-lp-bg'></div><div class='mc-lp-inner'>",
            "<header class='mc-lp-header'>",
            "<div class='mc-lp-brand'>",
            f"<div class='mc-lp-logo-wrap'>{logo_html}</div>",
            "<div class='mc-lp-brand-text'>",
            "<span class='mc-lp-brand-tag'>Plataforma integral</span>",
            "<p class='mc-lp-brand-name'>MediCare Enterprise PRO</p>",
            "</div></div>",
            "<div class='mc-lp-header-badge'>Salud domiciliaria · Operación · Auditoría</div>",
            "</header>",
            "<section class='mc-lp-hero'>",
            "<div class='mc-lp-hero-copy'>",
            "<p class='mc-lp-kicker'>Un solo entorno para todo el recorrido del paciente</p>",
            "<h1 class='mc-lp-h1'>Clínica, coordinación y respaldo legal <em>sin perder el control</em></h1>",
            "<p class='mc-lp-lead'>Ordená visitas, historia clínica, recetas con firma, emergencias, inventario, RRHH y documentación en una experiencia pensada para equipos en terreno y dirección.</p>",
            "<div class='mc-lp-pills'>",
            "<span class='mc-lp-pill'><strong>Web</strong> · celular y escritorio</span>",
            "<span class='mc-lp-pill'><strong>Roles</strong> · permisos por perfil</span>",
            "<span class='mc-lp-pill'><strong>Trazabilidad</strong> · auditoría lista</span>",
            "<span class='mc-lp-pill'><strong>App paciente</strong> · triage y alerta con GPS</span>",
            "</div></div>",
            "<div class='mc-lp-showcase'>",
            "<div class='mc-lp-showcase-in'>",
            "<p class='mc-lp-sc-title'>Flujo operativo unificado</p>",
            "<div class='mc-lp-sc-rows'>",
            "<div class='mc-lp-sc-row'><span class='mc-lp-sc-dot a'></span><div class='mc-lp-sc-txt'><b>Visita con fichada</b><span>GPS, agenda y registro de llegada/salida</span></div></div>",
            "<div class='mc-lp-sc-row'><span class='mc-lp-sc-dot b'></span><div class='mc-lp-sc-txt'><b>Historia en vivo</b><span>Vitales, evolución, estudios y escalas</span></div></div>",
            "<div class='mc-lp-sc-row'><span class='mc-lp-sc-dot c'></span><div class='mc-lp-sc-txt'><b>Cierre documental</b><span>PDF, consentimientos y exportes</span></div></div>",
            "</div></div></div>",
            "</section>",
            "<div class='mc-lp-stats'>",
            "<div class='mc-lp-stat'><div class='mc-lp-stat-val'>1</div><div class='mc-lp-stat-lbl'>Plataforma</div></div>",
            "<div class='mc-lp-stat'><div class='mc-lp-stat-val'>∞</div><div class='mc-lp-stat-lbl'>Pacientes y eventos</div></div>",
            "<div class='mc-lp-stat'><div class='mc-lp-stat-val'>GPS</div><div class='mc-lp-stat-lbl'>Fichadas verificables</div></div>",
            "<div class='mc-lp-stat'><div class='mc-lp-stat-val'>PDF</div><div class='mc-lp-stat-lbl'>Respaldo e impresión</div></div>",
            "</div>",
            "<div class='mc-lp-trust' role='list'>",
            "<span role='listitem'><strong>Seguridad</strong> HTTPS y sesión por usuario</span>",
            "<span role='listitem'><strong>2FA</strong> opcional por correo</span>",
            "<span role='listitem'><strong>Datos</strong> bajo control de tu organización</span>",
            "<span role='listitem'><strong>Soporte</strong> implementación y capacitación</span>",
            "</div>",
            "<h2 class='mc-lp-section-h'>Capacidades que venden por sí solas</h2>",
            "<p class='mc-lp-section-sub'>Menos fricción entre papel, WhatsApp y planillas: todo queda en un legajo coherente para el equipo y defendible frente a terceros.</p>",
            "<div class='mc-lp-bento'>",
            "<div class='mc-lp-b1'><div class='mc-lp-cell'><span class='mc-lp-ico'>\U0001F4CD</span><h4>Fichaje y visitas</h4><p>Coordenadas, agenda, estados y trazabilidad del día para quien trabaja en domicilio.</p></div></div>",
            "<div class='mc-lp-b2'><div class='mc-lp-cell'><span class='mc-lp-ico'>\U0001F4C4</span><h4>Historia clínica</h4><p>Vitales, evolución con firma, estudios adjuntos y pediatría con curvas.</p></div></div>",
            "<div class='mc-lp-b3'><div class='mc-lp-cell'><span class='mc-lp-ico'>\U0001F48A</span><h4>Medicación</h4><p>Recetas, administración, inventario y consumos vinculados al paciente.</p></div></div>",
            "<div class='mc-lp-b4'><div class='mc-lp-cell'><span class='mc-lp-ico'>\U0001F691</span><h4>Urgencias</h4><p>Triage, traslado, parte y PDF para archivo legal.</p></div></div>",
            "<div class='mc-lp-b5'><div class='mc-lp-cell'><span class='mc-lp-ico'>\u2696\ufe0f</span><h4>Auditoría</h4><p>Logs, legal, caja y RRHH con límites de datos para equipos modestos.</p></div></div>",
            "</div>",
            "<div class='mc-lp-split'>",
            "<div class='mc-lp-panel'><h3>Si la información está dispersa</h3><p>Suben errores, demoras y riesgos ante familias o auditorías. Centralizar en MediCare reduce fricción y refuerza la imagen profesional de tu servicio.</p></div>",
            "<div class='mc-lp-panel'><h3>Todo lo operativo en una app</h3><div class='mc-lp-checks'>",
            "<div class='mc-lp-check'>Visitas, guardias y coordinación en tiempo real</div>",
            "<div class='mc-lp-check'>Indicaciones, consentimientos y firmas</div>",
            "<div class='mc-lp-check'>Personal, fichajes y reportes</div>",
            "<div class='mc-lp-check'>Telemedicina y documentos descargables</div>",
            "</div></div></div>",
            "<div class='mc-lp-grid8'>",
            "<div class='mc-lp-mini'><div class='t'>\U0001F4F9 Telemedicina</div><p class='d'>Sala segura por paciente y día, integrada al legajo.</p></div>",
            "<div class='mc-lp-mini'><div class='t'>\u270D\ufe0f Firmas</div><p class='d'>Recetas y consentimientos con trazabilidad.</p></div>",
            "<div class='mc-lp-mini'><div class='t'>\U0001F476 Pediatría</div><p class='d'>Curvas y controles con historial ordenado.</p></div>",
            "<div class='mc-lp-mini'><div class='t'>\U0001F4A7 Balance</div><p class='d'>Ingresos y egresos por turno con alertas.</p></div>",
            "<div class='mc-lp-mini'><div class='t'>\U0001F4CB RRHH</div><p class='d'>Presentismo y duración de visitas.</p></div>",
            "<div class='mc-lp-mini'><div class='t'>\U0001F4B5 Caja</div><p class='d'>Prácticas, estados y exportación.</p></div>",
            "<div class='mc-lp-mini'><div class='t'>\U0001F3E5 Red</div><p class='d'>Profesionales e instituciones en un directorio.</p></div>",
            "<div class='mc-lp-mini'><div class='t'>\U0001F512 Roles</div><p class='d'>Accesos alineados a responsabilidad real.</p></div>",
            "</div>",
            "<div class='mc-lp-band'>",
            "<h3>Por qué mostrar MediCare en una reunión comercial</h3>",
            "<div class='mc-lp-benefits'>",
            "<div class='mc-lp-ben'><h5>Menos errores</h5><p>Datos claros y un solo lugar de verdad.</p></div>",
            "<div class='mc-lp-ben'><h5>Más control</h5><p>Coordinación y visibilidad para dirección.</p></div>",
            "<div class='mc-lp-ben'><h5>Más respaldo</h5><p>Registros y exportes listos para presentar.</p></div>",
            "<div class='mc-lp-ben'><h5>Escalable</h5><p>Desde independientes hasta redes.</p></div>",
            "</div></div>",
            "<div class='mc-lp-grid8'>",
            "<div class='mc-lp-mini'><div class='t'>Empresas de salud</div><p class='d'>Operación centralizada sin depender de planillas sueltas.</p></div>",
            "<div class='mc-lp-mini'><div class='t'>Profesionales</div><p class='d'>Registro móvil con menos pasos y más orden.</p></div>",
            "<div class='mc-lp-mini'><div class='t'>Coordinación</div><p class='d'>Agenda, equipo y auditoría para decidir rápido.</p></div>",
            "<div class='mc-lp-mini'><div class='t'>Emergencias</div><p class='d'>Evento, triage y traslado en el mismo sistema.</p></div>",
            "</div>",
            "<div class='mc-lp-close'>",
            "<div class='mc-lp-close-box'><h3>Presentación que vende</h3><p>Interfaz actual, usable en celular y PC, con foco clínico, operativo y legal. Ideal para demos a prestadores y contratistas.</p></div>",
            "<div class='mc-lp-close-box'><h3>Listo para demo</h3><p>Recorrido por módulos, roles y documentos descargables desde el primer encuentro.</p></div>",
            "</div>",
            "<div class='mc-lp-contact'>",
            "<h3>Implementación y soporte</h3>",
            "<p class='sub'>Contacto directo con el equipo</p>",
            "<div class='mc-lp-cgrid'>",
            "<div class='mc-lp-card'><p class='nm'>Enzo N. Girardi</p><p class='rl'>Desarrollo y soporte</p>",
            "<div class='mc-lp-btns'>",
            "<a class='mc-lp-wa' href='https://wa.me/5493584302024' target='_blank' rel='noopener'>WhatsApp</a>",
            "<a class='mc-lp-em' href='mailto:enzogirardi84@gmail.com'>Email</a>",
            "</div></div>",
            "<div class='mc-lp-card'><p class='nm'>Dario Lanfranco</p><p class='rl'>Implementación y contratos</p>",
            "<div class='mc-lp-btns'>",
            "<a class='mc-lp-wa' href='https://wa.me/5493584201263' target='_blank' rel='noopener'>WhatsApp</a>",
            "<a class='mc-lp-em' href='mailto:dariolanfrancoruffener@gmail.com'>Email</a>",
            "</div></div>",
            "</div></div>",
            "<div class='mc-lp-cta-wrap'>",
            "<p>Acceso al sistema</p>",
            "<p class='mc-lp-cta-sub'>Solo personal autorizado. Ante fallos de conexión, la app intenta modo local; "
            "si no podés continuar, contactá a soporte con captura del mensaje técnico.</p>",
            "</div>",
            "</div></div>",
        ]
    )
