"""Notas de versión breves para administradores (sin datos sensibles)."""

MC_APP_CHANGELOG = """
- **Correos transaccionales unificados (2026-04)**: `core/email_templates_medicare.py` con envoltorio oscuro común (preheader, kicker, alerta, pie). **2FA**, **recuperación de clave** y **confirmación de cambio de contraseña** comparten la misma base visual que la marca en app.
- **Recuperación de contraseña (2026-04)**: «Olvidé mi contraseña» envía **correo real por SMTP** con plantilla HTML (MediCare) y **token firmado** (enlace `?pwreset=` si configurás **APP_PUBLIC_URL**, más token copiable). Paso 2 en la misma pantalla: pegar token / enlace y guardar contraseña nueva. Secretos: mismos SMTP que 2FA; **PASSWORD_RESET_HMAC_SECRET** (o **EMAIL_2FA_HMAC_SECRET**); **PASSWORD_RESET_TTL_MINUTES** opcional (default 60).
- **UX 2026-04-12**: landing pre-login con franja de confianza (HTTPS, 2FA, datos, soporte), pill **App paciente** (triage/GPS), bloque **incidencia técnica** (mailto con asunto predefinido), texto de acceso solo personal autorizado y `prefers-reduced-motion` en hover. Login: expander *Problemas para ingresar o fallas del sistema*. Fallos de modulo: log `modulo_fallo`, sugerencias claras y traza en expander. Carga/guardado: avisos de nube/local sin exponer el error largo en el cuerpo principal; detalle en expander para soporte.
- **Mi equipo (móvil / tablet):** con **Modo celular viejo** o **anticolapso**, la grilla pasa a **ficha apilada** (nombre + estado, datos, acciones abajo), altura del panel de lista **400 px** (vs **520** en escritorio). PIN y avisos en recuadros **compactos** (CSS `.mc-mi-equipo-pin-*`) en lugar de `st.info`/`st.warning` altos. Ayuda larga en expander. Columnas escritorio algo más estrechas en estado/acciones.
- **Parche 2026-04-12 (Streamlit Cloud)**: login sin envío con usuario/contraseña vacíos (no cuenta fallo ni muestra mensaje genérico de credenciales); avisos de validación **fuera** del `st.form`; se quita `?modulo=` de la URL en pantalla de login (marcadores viejos). **Login de emergencia** con clave por defecto: además de `admin`, también **`enzogirardi`**; en **`USE_TENANT_SHARDS`** ese login carga monolito como `admin`. Opcional en secrets: `SUPERADMIN_EMERGENCY_LOGINS_EXTRA` (CSV o lista TOML). **Modo liviano (cliente)**: `streamlit.components.v1.html` **sin** argumento `key` (no existe en la API → `TypeError` en Cloud).
- **Seguridad multiclínica (Mi equipo)**: `filtrar_registros_empresa` sin mezcla multiclínica para Coordinador/Administrativo. **Menú Mi Equipo:** Coordinador y **Administrativo** (lectura/gestión permitida); **Operativo** no entra. **UI bajas:** `ok_bajas_ui = ok_gestionar and (puede_suspender or puede_eliminar)` — sin permiso de suspender **ni** eliminar en el rol, **no se renderizan** checkbox ni botones aunque otra capa devolviera True. **Suspender/Reactivar:** solo **SuperAdmin** (`puede_suspender_reactivar_usuario_mi_equipo`, NFKC + lista denegada). **Eliminar:** solo **SuperAdmin** y **Coordinador** (`puede_eliminar_cuenta_equipo`). **Actor** baja/suspensión: lista blanca en `actor_puede_modificar_usuario_equipo`. **Sesión:** `main.py` y Mi equipo re-sincronizan `rol`/`perfil` con `normalizar_usuario_sistema` cada corrida. **Normalización rol:** NFKC en `_texto_normalizado`; `administrador` → `Administrativo`. **Correo 2FA:** Coordinador + global. **Alta:** Coordinador + global. **Autoservicio:** baja/suspension propia bloqueada salvo global.
- **Modo anticolapso** (`core/anticolapso.py`): secret opcional **`MC_ANTICOLAPSO`** = `true` para todo el despliegue, o checkbox en sidebar **«Activar anticolapso esta sesion»**. Efectos: maximo **40** pacientes visibles sin busqueda (vs 80 normal) e **interfaz liviana** forzada. No borra datos ni modulos. Logo del sidebar: lectura tolerante a error de disco. **`guardar_datos`**: captura excepciones inesperadas, log tecnico y mensaje al usuario sin vaciar la sesion.
- **Alertas app paciente (triage)**: tabla Supabase `alertas_pacientes` + Edge `submit-alerta-paciente`. App Flutter: **NECESITO AYUDA** → rejilla de sintomas Rojo/Amarillo/Verde → cuenta 3 s → GPS. Panel web: metricas, filtros, mapa, CSV, estados Pendiente/En camino/Resuelto. Sidebar y banner rojos si hay **Rojo+Pendiente** para la clinica en sesion. **Rendimiento**: consulta a Supabase cacheada en sesion (default **30 s** entre refrescos; secret `APP_PACIENTE_ALERTAS_TTL_SECONDS`). Para apagar el polling: `APP_PACIENTE_ALERTAS_POLL = false`. Legacy `patient_alerts` opcional si ya estaba desplegado.
- UI: paleta teal/slate, alertas y mensajes de error más claros.
- Landing pre-login con diseño modular y tipografía dedicada.
- Panel de bienvenida y estados vacíos unificados (ampliado a más módulos).
- Registro técnico de fallos de conexión a base (sin datos clínicos).
- Historial, visitas, emergencias, red profesional, cierre diario y más con bloques vacíos coherentes.
- Opción **USE_TENANT_SHARDS**: una fila/archivo por clínica (nombre normalizado) para escalar sin un JSON monolítico gigante.
- **MONOLITO_LOGIN_ALLOWLIST** en secrets: logins que siguen usando el monolito global además de `admin`.
- **Contraseñas**: nuevas altas y cambios por PIN guardan **bcrypt** en `pass_hash` (campo `pass` en claro se migra al primer login OK). Secret opcional **PASSWORD_BCRYPT_ROUNDS** (10–15, default 12).
- **Anti fuerza bruta**: **MAX_LOGIN_ATTEMPTS**, **LOGIN_LOCKOUT_SECONDS**; **LOGIN_LOCKOUT_PERSIST** = `session` (solo navegador), `file` (`.streamlit/login_lockout_state.json` en el servidor) o `supabase` (tabla `app_login_lockout`; ver `supabase/app_login_lockout.sql`). En hosting efímero (p. ej. Streamlit Community Cloud) `file` puede perderse al reiniciar: en producción conviene `supabase`.
- **Despliegue**: conviene limitar tasa y tamaño de cuerpo delante de la app (p. ej. nginx, Cloudflare, AWS WAF) y exponer Streamlit solo por HTTPS.
- **2FA por correo** (opcional): `LOGIN_EMAIL_2FA = true` y SMTP (`SMTP_HOST`, `SMTP_PORT`, `SMTP_USER`, `SMTP_PASSWORD`, `SMTP_FROM`; puerto **465** = SSL, **587** = STARTTLS). Tras la contraseña correcta, **solo si el usuario tiene email válido en Mi equipo**, se envía un código de 6 dígitos; **sin email en ficha el ingreso sigue solo con contraseña** (no se bloquea la cuenta). Recomendado `EMAIL_2FA_HMAC_SECRET` (cadena larga). El acceso **admin de emergencia** por contraseña por defecto no pasa por 2FA si el usuario no tiene email. El correo de código incluye versión **HTML** además del texto plano. Log técnico `login_ok_2fa_omitido_sin_email_en_ficha` cuando 2FA está activo y se omite por falta de correo.
- **Política de contraseñas**: `PASSWORD_MIN_LENGTH` (default **8**, rango 4–128); opcional `PASSWORD_REQUIRE_LETTER_AND_DIGIT` para exigir letra y número en altas y recuperación. Los emails para 2FA se validan con formato **RFC-like** básico.
- **Sesión**: al cerrar sesión, inactividad o suspensión de clínica se limpian también desafío 2FA, lockout en memoria y flags auxiliares de login, y se **vacían los datos clínicos en memoria** (`vaciar_datos_app_en_sesion`) para equipos compartidos.
- **Anti enumeración**: mismo mensaje ante usuario/contraseña incorrectos en login; en recuperación por PIN, mensaje único ante datos inválidos (salvo política de contraseña, que sigue siendo explícita). **LOGIN_FAIL_JITTER_MS** (default ~45 ms, `0` = off): pausa aleatoria breve tras intentos fallidos que cuentan en el contador.
- **Auditoría técnica**: evento `password_reset_via_pin_ok` al cambiar clave por PIN con éxito.
- **Volver a la Publicidad** (sidebar): además de ocultar la app, vacía datos clínicos en memoria y estado de login/2FA (misma idea que cerrar sesión en equipo compartido).
- **Arranque monolito** (sin `USE_TENANT_SHARDS`): ya no se llama a `cargar_datos()` al iniciar la app; la base se descarga solo al **login** o **olvidé contraseña**, igual que la idea del modo multiclínica (menos datos en sesión antes de autenticar).
"""
