apiVersion: v1
kind: Service
metadata:
  name: nextgen-api
  namespace: nextgen
spec:
  selector:
    app: nextgen-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: ClusterIP
