apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: nextgen-api-hpa
  namespace: nextgen
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: nextgen-api
  minReplicas: 3
  maxReplicas: 15
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 65
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: nextgen-worker-imports-hpa
  namespace: nextgen
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: nextgen-worker-imports
  minReplicas: 2
  maxReplicas: 12
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
